name: Integrated Physicians Medical Group Inc.
favicon: null
layout_spectrum: 0.34366
typography_spectrum: 0.8225257303565741
title: We are a group of diverse doctors committed to finding the safest most effective treatments for you.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#010101'
    - '#00abca'
    - '#9ebabf'
    - '#364144'
  brandStrength: 0.625
  lightness: 0.625
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
