name: Integrated Physicians Medical Group Inc.
favicon: null
layout_spectrum: 0.659272151067853
typography_spectrum: 0.8225257303565741
title: We are a group of diverse doctors committed to finding the safest most effective treatments for you.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.30756212561391294
  lightness: 0.46371562709100544
  saturation: 0.8588501543272287
  rhythmicContrast: 0.029765937011688948
purpose: []
